export const productTitles = [
  "Signature Oxford Slim-Fit Shirt",
  "Heritage Selvedge Denim Jeans",
  "Lightweight Merino Wool Sweater",
  "Technical Waterproof Parka",
  "Premium Linen Summer Blazer",
  "Essential Cotton Crewneck Tee",
  "Stretch Chino Trousers",
  "Vintage Graphic Print Hoodie",
  "Italian Leather Belt",
  "Performance Workout Shorts",
  "Floral Silk Wrap Dress",
  "High-Waisted Pleated Trousers",
  "Oversized Cashmere Cardigan",
  "Classic Trench Coat",
  "Bohemian Embroidered Blouse",
  "Sculpting Yoga Leggings",
  "Satin Midi Skirt",
  "Tailored Linen Vest",
  "Classic Denim Jacket",
  "Evening Sequin Mini Dress",
  "Organic Cotton Baby Onesie",
  "Denim Overalls for Kids",
  "Toddler Canvas Sneakers",
  "Cozy Fleece Bear Hoodie",
  "Floral Print Cotton Dress",
  "Rainy Day Waterproof Boots",
  "Graphic T-Shirt - Dino Adventure",
  "Baby Knit Blanket",
  "Striped Swimwear Set",
  "Smart Cotton Button-Up Shirt",
  "Urban Explorer White Sneakers",
  "Classic Leather Chelsea Boots",
  "Performance Mesh Running Shoes",
  "Pointed Toe Stiletto Heels",
  "Casual Suede Loafers",
  "Handcrafted Wingtip Oxfords",
  "Rugged Mountain Hiking Boots",
  "Comfort Foam Sliders",
  "Platform Velvet Ankle Boots",
  "Espadrille Wedge Sandals",
  "Polarized Aviator Sunglasses",
  "Silk Twill Square Scarf",
  "Woven Fedora Straw Hat",
  "Embossed Leather Card Holder",
  "Knit Wool Beanie",
  "Chunky Gold Link Necklace",
  "Reversible Leather Belt",
  "Velvet Hair Bow Clip",
  "Cotton Canvas Tote Bag",
  "Suede Touchscreen Gloves",
  "Executive Leather Briefcase",
  "Quilted Chain Crossbody Bag",
  "Urban Roll-Top Backpack",
  "Continental Zip-Around Wallet",
  "Weekend Canvas Duffle Bag",
  "Minimalist Bifold Wallet",
  "Boho Fringe Suede Bag",
  "Laptop Sleeve - 14 Inch",
  "Miniature Top-Handle Bag",
  "Anti-Theft Travel Backpack",
  "18K Gold Plated Hoop Earrings",
  "Diamond Solitaire Pendant",
  "Stacked Bead Bracelet Set",
  "Personalized Initial Ring",
  "Vintage Pearl Drop Earrings",
  "Statement Chunky Cuff",
  "Layered Celestial Necklace",
  "Men's Black Onyx Signet Ring",
  "Dainty Snake Chain Anklet",
  "Crystal Teardrop Brooch",
  "Chronograph Steel Sports Watch",
  "Minimalist Mesh Strap Watch",
  "Classic Leather Dress Watch",
  "Automatic Skeleton Watch",
  "Smart Fitness Tracker - Pro",
  "Pilot's Large Dial Watch",
  "Diamond Bezel Evening Watch",
  "Diver's Waterproof Watch",
  "Retro Digital Gold Watch",
  "Titanium Ultra-Light Watch",
  "Hyaluronic Acid Glow Serum",
  "Matte Velvet Lipstick - Ruby Red",
  "Organic Beard Oil - Sandalwood",
  "Natural Clay Face Mask",
  "Nourishing Night Cream",
  "SPF 50 Invisible Sunscreen",
  "Rose Water Face Mist",
  "Professional Eye Shadow Palette",
  "Sulfate-Free Strengthening Shampoo",
  "Whipped Shea Body Butter",
  "Hand-Poured Soy Wax Candle",
  "Luxury Egyptian Cotton Towel Set",
  "Minimalist Ceramic Coffee Mug",
  "Weighted Anxiety Blanket",
  "Smart Indoor Herb Garden",
  "Woven Decorative Throw Pillow",
  "Insulated Stainless Steel Bottle",
  "Aura Ultrasonic Essential Oil Diffuser",
  "Linen Bed Sheet Set - Queen",
  "Sleek Metal Table Lamp"
];
