export const productTitles = [
  "ELYJEN Air-Stride Pro",
  "Urban Velocity Sneakers",
  "CloudWalk Elite Performance",
  "Stealth Neo-Classic Lows",
  "Heritage Canvas High-Tops",
  "Apex Runner Gen-3",
  "Midnight Suede Lifestyle",
  "Volt-Charge Sport Sneakers",
  "Minimalist Leather Trainers",
  "Lunar-Flex Cross-Trainers",
  "Summit Trail Hiker Lows",
  "Arctic Breeze Breathable Mesh",
  "Carbon-Fiber Speed Pro",
  "Vintage Streetwear Mids",
  "Titan-Shield Waterproof Sneaks",
  "Zen-Flow Yoga Lifestyle Shoes",
  "Horizon Ombre Knit Runners",
  "Fusion-Core Hybrid Sneakers",
  "Neo-Grip Skateboard Lows",
  "Prism Reflective Night-Runners",
  "Eco-Stride Sustainable Knit",
  "Kids' Turbo-Jump Light-ups",
  "Toddler Comfy-Step Velcros",
  "Youth All-Star Court Shoes",
  "Baby Soft-Sole First-Steps",
  "Velvet-Touch Evening Sneakers",
  "Platform Glow Fashion Sneakers",
  "Metallic Silver Space-Runners",
  "Glitter-Dash Kids' Collection",
  "Chunky Retro Dad-Shoes",
  "Signature Gold-Leaf Limited",
  "Pro-Grip Basketball Highs",
  "Sling-Back Mesh Summer Sneakers",
  "Slip-On Comfort Sliders",
  "Premium Nappa Leather Lows",
  "Desert Sand Tactical Boots",
  "Ocean Wave Recycled Plastic Sneakers",
  "Luxe-Satin Ribbon Lace-ups",
  "Studded Punk-Rock High-Tops",
  "Floral Bloom Spring Sneakers",
  "Marble-Print Artistic Lows",
  "Neon-Glow Party Sneakers",
  "Classic Gum-Sole Trainers",
  "Python-Embossed Luxe Sneakers",
  "Thermal-Warm Winter Sneaks",
  "Ultra-Light Marathon Elites",
  "Court-Master Tennis Shoes",
  "Street-Savvy Canvas Mules",
  "Dynamic Fit Compression Sneakers",
  "Elegance Suede Dress Sneakers"
];
